version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: FIDBaru2.3
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - laravel

  nginx:
    image: nginx:stable-alpine
    container_name: FIDBaru2.3
    ports:
      - "8000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www
    networks:
      - laravel

  db:
    image: mysql:5.7
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3307:3307"
    environment:
      MYSQL_DATABASE: FIDBaru5
      MYSQL_USER: root
      MYSQL_PASSWORD: Joe2dohi1
      MYSQL_ROOT_PASSWORD: Joe2dohi1
    volumes:
      - mysql-db:/var/lib/mysql
    networks:
      - laravel

networks:
  laravel:
    driver: bridge

volumes:
  mysql-db:
